scan:
  scanners:
    - vuln
    - secret
    - misconfig
  skip-dirs:
    # VCS
    - .git

    # Node.js / Next.js
    - node_modules
    - .next
    - dist
    - build
    - coverage
    - .turbo

    # Python
    - .venv
    - __pycache__
    - .pytest_cache
    - .ruff_cache

    # Go
    - vendor
    - bin

    # C#/.NET
    - obj

severity:
  - CRITICAL
  - HIGH

ignore-unfixed: true
dependency-tree: true
timeout: 10m

pkg:
  include-dev-deps: true
