name: Bug report
description: An unexpected error or behavior
title: "[Bug] "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Create a bug report.

  - type: dropdown
    id: service
    attributes:
      label: Service
      description: Which service is this bug related to?
      options:
        - Authingway
        - Clearingway
        - Findingway
        - Moddingway
        - Naurffxiv
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: observed-behavior
    attributes:
      label: Observed behavior
      description: A clear and concise description of what happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
