name: "Check QA Approval Gate"
description: "Blocks merge on QA PRs until 2 approvals are received (code reviewer + QA team)"
inputs:
  github-token:
    description: "GitHub Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check QA Approval Gate
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const script = require('${{ github.action_path }}/index.js');
          await script({ github, context, core });
